// demo0/frontend/src/components/TodoItem.vue
<template>
	<div class="todo-item" :class="{ completed: todo.completed }">
		<div class="todo-content">
			<input
				type="checkbox"
				:checked="todo.completed"
				@change="handleToggle"
				class="todo-checkbox"
			/>
			<div class="todo-info">
				<h3 class="todo-title">{{ todo.title }}</h3>
				<p v-if="todo.description" class="todo-description">
					{{ todo.description }}
				</p>
				<span class="todo-date">
					{{ formattedDate }}
				</span>
			</div>
		</div>
		<button @click="handleDelete" class="btn-delete">
			🗑️ 删除
		</button>
	</div>
</template>

<script>
import { computed } from 'vue'

export default {
	name: 'TodoItem',
	props: {
		// 接收待办事项对象
		todo: {
			type: Object,
			required: true,
		},
		// 接收日期格式化函数
		formatDate: {
			type: Function,
			required: true,
		},
	},
	emits: ['toggle', 'delete'], // 声明事件
	setup(props, { emit }) {
		/**
		 * 计算属性：格式化的日期
		 */
		const formattedDate = computed(() => {
			return props.formatDate(props.todo.created_at)
		})

		/**
		 * 处理复选框切换
		 */
		const handleToggle = () => {
			emit('toggle', props.todo)
		}

		/**
		 * 处理删除
		 */
		const handleDelete = () => {
			if (confirm('确定要删除这个任务吗？')) {
				emit('delete', props.todo.id)
			}
		}

		return {
			formattedDate,
			handleToggle,
			handleDelete,
		}
	},
}
</script>

<style scoped>
.todo-item {
	display: flex;
	justify-content: space-between;
	align-items: center;
	padding: 16px;
	border: 2px solid #f0f0f0;
	border-radius: 8px;
	transition: all 0.3s;
}

.todo-item:hover {
	border-color: #667eea;
	box-shadow: 0 2px 8px rgba(102, 126, 234, 0.2);
}

.todo-item.completed {
	opacity: 0.6;
	background: #f9f9f9;
}

.todo-content {
	display: flex;
	align-items: center;
	gap: 16px;
	flex: 1;
}

.todo-checkbox {
	width: 20px;
	height: 20px;
	cursor: pointer;
}

.todo-info {
	flex: 1;
}

.todo-title {
	font-size: 18px;
	color: #333;
	margin-bottom: 4px;
}

.todo-item.completed .todo-title {
	text-decoration: line-through;
	color: #999;
}

.todo-description {
	color: #666;
	font-size: 14px;
	margin-bottom: 8px;
}

.todo-date {
	color: #999;
	font-size: 12px;
}

.btn-delete {
	background: #ff6b6b;
	color: white;
	padding: 8px 16px;
	white-space: nowrap;
	border: none;
	border-radius: 6px;
	cursor: pointer;
	transition: background 0.3s;
}

.btn-delete:hover {
	background: #ff5252;
}
</style>

// demo0/frontend/src/components/TodoItem.tsx
import type { Todo } from '../services/api'

interface TodoItemProps {
    todo: Todo
    selected: boolean
    formatDate: (dateString: string) => string
    onToggle: (todo: Todo) => void
    onDelete: (id: number) => void
    onToggleSelect: (id: number) => void
}

function TodoItem({ todo, selected, formatDate, onToggle, onDelete, onToggleSelect }: TodoItemProps) {
    const handleToggle = (): void => {
        onToggle(todo)
    }

    const handleDelete = (): void => {
        if (confirm('确定要删除这个任务吗？')) {
            onDelete(todo.id)
        }
    }

    return (
        <div className={`group flex items-center gap-3 px-5 py-3.5 border-b border-gray-100 last:border-b-0 transition-colors duration-150 hover:bg-gray-50 ${selected ? 'bg-indigo-50' : ''} ${todo.completed ? 'opacity-65' : ''}`}>
            <input
                type="checkbox"
                checked={selected}
                onChange={() => onToggleSelect(todo.id)}
                className="size-4 cursor-pointer accent-indigo-500 shrink-0"
            />

            <button
                className={`size-5.5 rounded-full border-2 p-0 flex items-center justify-center shrink-0 transition-all duration-200 ${todo.completed ? 'bg-indigo-500 border-indigo-500 text-white' : 'border-gray-300 bg-transparent hover:border-indigo-500'}`}
                onClick={handleToggle}
                aria-label={todo.completed ? '标记为未完成' : '标记为完成'}
            >
                {todo.completed && (
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                        <polyline points="20 6 9 17 4 12"></polyline>
                    </svg>
                )}
            </button>

            <div className="flex-1 min-w-0 flex items-center justify-between gap-3">
                <div className="min-w-0">
                    <span className={`text-[15px] font-medium leading-relaxed ${todo.completed ? 'line-through text-gray-400' : 'text-[#1a1a2e]'}`}>
                        {todo.title}
                    </span>
                    {todo.description && (
                        <p className="text-[13px] text-gray-500 mt-0.5 leading-relaxed overflow-hidden text-ellipsis whitespace-nowrap">{todo.description}</p>
                    )}
                </div>
                <span className="text-xs text-gray-400 whitespace-nowrap shrink-0">{formatDate(todo.created_at)}</span>
            </div>

            <button onClick={handleDelete} className="flex items-center justify-center size-8 p-0 bg-transparent text-gray-300 rounded-md shrink-0 opacity-0 group-hover:opacity-100 transition-all duration-150 hover:bg-red-50 hover:text-red-600" aria-label="删除任务">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="3 6 5 6 21 6"></polyline>
                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                </svg>
            </button>
        </div>
    )
}

export default TodoItem
